_url = 'https://peos.dmw.gov.ph/controller/login.php'
_logout = 'https://peos.dmw.gov.ph/logout.php'
_patch_url = 'https://peos.dmw.gov.ph/hhw.php'
_module_url = 'https://peos.dmw.gov.ph/controller/selectQuestionsHHW.php'
_check_answer = 'https://peos.dmw.gov.ph/controller/checkAnswerHHW.php'
_get_cert = 'https://peos.dmw.gov.ph/controller/selectModuleHHW.php'
API_TOKEN = '5754818149:AAFtrIQGHaWTBkPicok0yt0e1kNsn4OuqQQ'